services:
  app-test:
    image: romira/zenita:test
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /var/www/app
    environment:
      MYSQL_HOST: db-test
      MYSQL_PORT: 3306
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
      IMAGE_BASE_URL: http://localhost:8080
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www/app
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - "3360:3306"
    volumes:
      - db-test-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  db-test-data:
