name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: "romira/zenita:v2"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup
        run: make init-test

      - name: Run test suite
        run: docker compose exec app composer run-script test
